---
title: "Modeling"
---
<style type="text/css">
  body{
  font-size: 16pt;
}
</style>

```{r include=FALSE}

knitr::opts_chunk$set(echo = FALSE, error = FALSE, warning = FALSE,
                      message = FALSE)

```

```{r load_libraries}

library(tidyverse)

library(tidymodels)

library(baguette)

library(embed)

library(workflowsets)

```

```{r parameters}

professions = c(
  "manager",
  "business",
  "financialop",
  "computer",
  "architect",
  "scientist",
  "socialworker",
  "postseceduc",
  "legaleduc",
  "artist",
  "lawyerphysician",
  "healthcare",
  "healthsupport",
  "protective",
  "foodcare",
  "building",
  "sales",
  "officeadmin",
  "farmer",
  "constructextractinstall",
  "production",
  "transport"
)

```

```{r load_data}

data("train_set")

train_set_transformed = train_set %>%
  rename(ID = 1) %>%
  pivot_longer(cols = all_of(professions), names_to = "profession") %>%
  filter(value == 1) %>%
  select(-value) %>%
  mutate(profession = factor(profession))%>% 
  rowwise() %>% 
  mutate(white = 1 - sum(c_across(c("black","hisp","otherrace")))) %>% 
  ungroup() %>% 
  pivot_longer(cols = c(c("black","hisp","otherrace","white")),
               names_to = "race") %>% 
  filter(value == 1) %>% 
  select(-value) %>% 
  rowwise() %>% 
  mutate(west = 1 - sum(c_across(c("northeast","northcentral","south")))) %>% 
  ungroup() %>% 
  pivot_longer(cols = c(c("northeast","northcentral","south","west")),
               names_to = "area") %>%
  filter(value == 1) %>%
  select(-value) %>%
  mutate(male = 1 - female) %>% 
  pivot_longer(cols = c(c("male","female")),
               names_to = "sex") %>%
  filter(value == 1) %>%
  select(-value) %>% 
  identity()

data("test_set")

test_set_transformed = test_set %>%
  rename(ID = 1) %>%
  pivot_longer(cols = all_of(professions), names_to = "profession") %>%
  filter(value == 1) %>%
  select(-value) %>%
  mutate(profession = factor(profession))%>% 
  rowwise() %>% 
  mutate(white = 1 - sum(c_across(c("black","hisp","otherrace")))) %>% 
  ungroup() %>% 
  pivot_longer(cols = c(c("black","hisp","otherrace","white")),
               names_to = "race") %>% 
  filter(value == 1) %>% 
  select(-value) %>% 
  rowwise() %>% 
  mutate(west = 1 - sum(c_across(c("northeast","northcentral","south")))) %>% 
  ungroup() %>% 
  pivot_longer(cols = c(c("northeast","northcentral","south","west")),
               names_to = "area") %>%
  filter(value == 1) %>%
  select(-value) %>%
  mutate(male = 1 - female) %>% 
  pivot_longer(cols = c(c("male","female")),
               names_to = "sex") %>%
  filter(value == 1) %>%
  select(-value) %>% 
  identity()


```

```{r preprocessing}


full_recipe = recipe(lnwage ~ ., data = train_set_transformed) %>%
update_role(ID,new_role = "id variable") %>%
step_rm(ends_with("sq")) %>%
step_mutate(total_exp = expf + expp + 0.001) %>%
step_mutate(part_share = expp / total_exp) %>%
step_YeoJohnson(all_numeric(), -all_outcomes()) %>%
step_mutate_at(c("expf","expp","edyrs","total_exp","part_share"),
fn = list(sq = ~. ^ 2)) %>%
step_log(c("expf","expp","edyrs","total_exp","part_share"),offset = 0.01) %>%
step_normalize(all_numeric(),-all_outcomes()) %>%
step_lencode_glm(profession,outcome = vars(lnwage)) %>%
step_dummy(c("race","area","sex")) %>%
step_interact(~edyrs:starts_with("race")) %>%
step_interact(~starts_with("sex"):starts_with("race"))


complete_recipe = recipe(lnwage ~ ., data = train_set_transformed) %>% 
  update_role(ID,new_role = "id variable") %>% 
  step_rm(ends_with("sq")) %>% 
  step_mutate(total_exp = expf + expp + 0.001) %>% 
  step_mutate(part_share = expp / total_exp) %>% 
  step_YeoJohnson(all_numeric(), -all_outcomes()) %>% 
  step_mutate_at(c("expf","expp","edyrs","total_exp","part_share"),
                 fn = list(sq = ~. ^ 2)) %>% 
  step_normalize(all_numeric(),-all_outcomes()) %>%
  step_lencode_glm(profession,outcome = vars(lnwage)) %>% 
  step_dummy(c("race","area","sex")) %>% 
  step_interact(~edyrs:starts_with("race"))


basic_recipe = recipe(lnwage ~ ., data = train_set_transformed) %>% 
  update_role(ID,new_role = "id variable") %>% 
  step_rm(ends_with("sq")) %>% 
  step_mutate(total_exp = expf + expp + 0.001) %>% 
  step_mutate(part_share = expp / total_exp) %>% 
  step_rm(c("expf","expp")) %>% 
  step_YeoJohnson(all_numeric(), -all_outcomes()) %>% 
  step_mutate_at(c("edyrs","total_exp","part_share"),
                 fn = list(sq = ~. ^ 2)) %>% 
  step_normalize(all_numeric(),-all_outcomes()) %>%
  step_lencode_glm(profession,outcome = vars(lnwage)) %>% 
  step_dummy(c("race","area","sex")) %>% 
  step_interact(~edyrs:starts_with("race"))


```

```{r set_models_spec}

lasso_model = linear_reg(penalty = tune(), mixture = 1) %>% 
  set_engine("glmnet")

```


```{r test_drive, eval=FALSE}


temp_data = basic_recipe %>% 
  prep() %>% 
  bake(train_set_transformed)

models_set = workflow_set(
  preproc = list(basic = basic_recipe),
  models = list(lasso = lasso_model)
)

resample_res = models_set %>%
  workflow_map(
    fn = "tune_grid",
    resamples = vfold_cv(train_set_transformed, 2),
    grid = 2
  )

```




```{r set_cross_validation_and_tuning}

cv_folds = train_set_transformed %>% 
  vfold_cv(v = 10, repeats = 5)

param_grid = grid_regular(penalty(),levels = 50)


```

```{r estimation}

models_set = workflow_set(
  preproc = list(basic = basic_recipe,complete_recipe = complete_recipe,
                 full_recipe = full_recipe),
  models = list(lasso = lasso_model)
)

resample_res = models_set %>%
  workflow_map(
    fn = "tune_grid",
    resamples = cv_folds,
    grid = param_grid,
    control = control_grid(parallel_over = "everything")
  )




```

```{r evaluation}

resample_res %>% 
  rank_results(rank_metric = "rmse") %>% 
  filter(.metric == "rmse") %>% 
  select(wflow_id,.config,mean, rank) %>% 
  mutate(mean = mean ^ 2) %>% 
  ggplot(aes(x = rank, y = mean)) + 
  geom_point()

```

```{r prediction, eval=FALSE}

test_split = make_splits(list(analysis = 1:1000, assessment = 1001:1500),
                         bind_rows(train_set_transformed, test_set_transformed))


best_model = resample_res %>% 
  pull_workflow_set_result("basic_lasso") %>% 
  select_best(metric = "rmse")

pred = resample_res %>% 
  pull_workflow("basic_lasso") %>% 
  finalize_workflow(best_model) %>% 
  last_fit(test_split)


test_set_transformed %>% 
  select("ID") %>% 
  bind_cols(pred$.predictions[[1]] %>% 
  select(lnwage = .pred)) %>% 
  write_csv("C:\\Users\\internet\\Desktop\\yaakov.csv")


```

